server:
  port: 8086

spring:
  application:
    name: DEMO-SERVICE
#  config:
#    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

# for eureka client
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    registry-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

