server:
  port: 8888
spring:
  application:
    name: CONFIG-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/somyajoshi5/config-repo
          clone-on-start: true

# for eureka client
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    registry-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

